/**
 * corporateMasterService.ts
 *
 * Central Corporate ERP Master Data Repository (IFS / SAP / Central Database).
 * Provides verified master data records across all company projects & central depots.
 * Project sites / tenants import master records from this central catalog instead
 * of typing ad-hoc manual records.
 */

export interface CorporateEquipment {
  code: string;
  name: string; // Description
  searchKey?: string;
  costRate?: number;
  currency?: string;
  type: string;
  model: string;
  registrationNo: string;
  capacity: string;
  sourceProject: string;
  status: 'active';
}

export interface CorporateBusinessPartner {
  code: string;
  name: string;
  type: string;
  contactPerson: string;
  phone: string;
  email: string;
  address: string;
  sourceProject: string;
  rating: string;
}

export interface CorporateEmployee {
  employeeCode: string;
  callingName: string;
  fullName: string;
  nicNo: string;
  tradeGroup: string;
  isOperator?: boolean;
  licenseNo?: string;
  businessPartnerCode?: string; // e.g. "BP1004093" (Number/Code)
  businessPartnerName?: string; // e.g. "Aruna Builders (Pvt) Ltd"
  businessPartner?: string; // Backwards compatibility for UI
  currentWorkingProject?: string;
  sourceProject?: string;
  epfNo?: string;
  dailyRate?: number;
  skillLevel?: string;
}

export interface CorporateActivityCode {
  code: string;
  description: string;
  searchKey?: string;
  activityType?: string; // 'Work Package' | 'WBS Element' | 'Control Account' | 'Planning Package' | 'Milestone'
  unit?: string;
  timeUnit?: string;
  currentWorkingProject?: string;
  sourceProject?: string;
  tradeGroup?: string;
}

export interface CorporateProject {
  projectCode: string;
  description: string;
  searchKey: string;
  projectManager?: string;
  status: 'Active' | 'Closed' | 'Suspended';
  addressCode?: string;
  projectName?: string;
  enterpriseUnit?: string; // 'BDG001' | 'RDS001' | 'BRG001' | 'WRK001'
  divisionType?: string;
  currency?: string;
}

// ── 1. Central Corporate Equipment Master ─────────────────────────────────────
export const CORPORATE_EQUIPMENT_CATALOG: CorporateEquipment[] = [
  // ── Maga ERP Live Central Master Records ──
  {
    code: 'MCBW0005',
    name: 'DYNAMIC',
    searchKey: 'DYNAMIC',
    costRate: 200.0,
    currency: 'LKR',
    type: 'Compaction',
    model: 'DYNAMIC PLATE',
    registrationNo: 'CBW-0005',
    capacity: 'Plate Compactor 90kg',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MEXC0011',
    name: 'EXCAVATOR KOBELCO SOLAR 220 LC',
    searchKey: 'EXCAVATOR KOBELC',
    costRate: 1500.0,
    currency: 'LKR',
    type: 'Heavy machinery',
    model: 'KOBELCO SOLAR 220 LC',
    registrationNo: 'EXC-0011',
    capacity: '22 Tons / 1.0 m³',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MHOP0012',
    name: 'PASSENGER HOIST LEYONG-GJJ 2 C',
    searchKey: 'PASSENGER HOIST',
    costRate: 216000.0,
    currency: 'LKR',
    type: 'Hoist',
    model: 'LEYONG-GJJ 2 C',
    registrationNo: 'HOP-0012',
    capacity: '2.0 Tons Dual Cage',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MHOP0013',
    name: 'PASSENGER HOIST LEYONG-GJJ 2 C',
    searchKey: 'PASSENGER HOIST',
    costRate: 216000.0,
    currency: 'LKR',
    type: 'Hoist',
    model: 'LEYONG-GJJ 2 C',
    registrationNo: 'HOP-0013',
    capacity: '2.0 Tons Dual Cage',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MMCA0012',
    name: 'HONDA CIVIC',
    searchKey: 'HONDA CIVIC',
    costRate: 33000.0,
    currency: 'LKR',
    type: 'Vehicle',
    model: 'HONDA CIVIC',
    registrationNo: 'WP-CAD-1212',
    capacity: 'Staff Transport Sedan',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MMCA0014',
    name: 'HONDA CIVIC',
    searchKey: 'HONDA CIVIC',
    costRate: 33000.0,
    currency: 'LKR',
    type: 'Vehicle',
    model: 'HONDA CIVIC',
    registrationNo: 'WP-CAD-1414',
    capacity: 'Staff Transport Sedan',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MRAM0157',
    name: 'DAYNAPAC',
    searchKey: 'DAYNAPAC',
    costRate: 1250.0,
    currency: 'LKR',
    type: 'Compaction',
    model: 'DAYNAPAC LT',
    registrationNo: 'RAM-0157',
    capacity: 'Tamping Rammer 75kg',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MRAM0599',
    name: 'MASTERPAC',
    searchKey: 'MASTERPAC',
    costRate: 1250.0,
    currency: 'LKR',
    type: 'Compaction',
    model: 'MASTERPAC PMR68',
    registrationNo: 'RAM-0599',
    capacity: 'Tamping Rammer 68kg',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MRAM0600',
    name: 'MASTERPAC',
    searchKey: 'MASTERPAC',
    costRate: 1250.0,
    currency: 'LKR',
    type: 'Compaction',
    model: 'MASTERPAC PMR68',
    registrationNo: 'RAM-0600',
    capacity: 'Tamping Rammer 68kg',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MRAM0601',
    name: 'MASTERPAC',
    searchKey: 'MASTERPAC',
    costRate: 1250.0,
    currency: 'LKR',
    type: 'Compaction',
    model: 'MASTERPAC PMR68',
    registrationNo: 'RAM-0601',
    capacity: 'Tamping Rammer 68kg',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MRAM0602',
    name: 'MASTERPAC',
    searchKey: 'MASTERPAC',
    costRate: 1250.0,
    currency: 'LKR',
    type: 'Compaction',
    model: 'MASTERPAC PMR68',
    registrationNo: 'RAM-0602',
    capacity: 'Tamping Rammer 68kg',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MRAM0603',
    name: 'MASTERPAC',
    searchKey: 'MASTERPAC',
    costRate: 1250.0,
    currency: 'LKR',
    type: 'Compaction',
    model: 'MASTERPAC PMR68',
    registrationNo: 'RAM-0603',
    capacity: 'Tamping Rammer 68kg',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MRVI0072',
    name: 'VIBRATORY ROLLER CATERPILLAR C',
    searchKey: 'VIBRATORY ROLLER',
    costRate: 1500.0,
    currency: 'LKR',
    type: 'Compaction',
    model: 'CATERPILLAR CS533E',
    registrationNo: 'RVI-0072',
    capacity: '12.5 Tons Single Drum',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MRVI0073',
    name: 'VIBRATORY ROLLER CATERPILLAR C',
    searchKey: 'VIBRATORY ROLLER',
    costRate: 1500.0,
    currency: 'LKR',
    type: 'Compaction',
    model: 'CATERPILLAR CS533E',
    registrationNo: 'RVI-0073',
    capacity: '12.5 Tons Single Drum',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MTBW0023',
    name: 'TRACTOR BOWSER SANPAC',
    searchKey: 'TRACTOR BOWSER',
    costRate: 6000.0,
    currency: 'LKR',
    type: 'Transport',
    model: 'SANPAC 4WD TRACTOR',
    registrationNo: 'TBW-0023',
    capacity: '6000 Liters Bowser',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MTCR0003',
    name: 'CRANE-TOWER LIEBHERR HC256 HC',
    searchKey: 'CRANE-TOWER LIEB',
    costRate: 0.0,
    currency: 'LKR',
    type: 'Crane',
    model: 'LIEBHERR 256 HC',
    registrationNo: 'TCR-0003',
    capacity: '10 Tons Max / 70m Jib',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MTMX0072',
    name: 'ISUZU NRR32C',
    searchKey: 'ISUZU NRR32C',
    costRate: 350.0,
    currency: 'LKR',
    type: 'Concrete',
    model: 'ISUZU NRR32C TRANSIT',
    registrationNo: 'TMX-0072',
    capacity: '6 m³ Drum Mixer',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MTMX0073',
    name: 'ISUZU NRR32C',
    searchKey: 'ISUZU NRR32C',
    costRate: 350.0,
    currency: 'LKR',
    type: 'Concrete',
    model: 'ISUZU NRR32C TRANSIT',
    registrationNo: 'TMX-0073',
    capacity: '6 m³ Drum Mixer',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MTMX0077',
    name: 'ISUZU U-FK337C',
    searchKey: 'ISUZU U-FK337C',
    costRate: 350.0,
    currency: 'LKR',
    type: 'Concrete',
    model: 'ISUZU U-FK337C TRANSIT',
    registrationNo: 'TMX-0077',
    capacity: '6 m³ Drum Mixer',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MTMX0078',
    name: 'ISUZU U-NRR32C',
    searchKey: 'ISUZU U-NRR32C',
    costRate: 350.0,
    currency: 'LKR',
    type: 'Concrete',
    model: 'ISUZU U-NRR32C TRANSIT',
    registrationNo: 'TMX-0078',
    capacity: '6 m³ Drum Mixer',
    sourceProject: 'Maga - CWS',
    status: 'active',
  },
  {
    code: 'MEXC0012',
    name: 'CAT 320D Hydraulic Excavator',
    type: 'Heavy machinery',
    model: 'CAT 320D2 GC',
    registrationNo: 'WP-SP-4821',
    capacity: '20 Tons / 1.0 m³',
    sourceProject: 'Central Equipment Yard - Peliyagoda',
    status: 'active',
  },
  {
    code: 'MEXC0015',
    name: 'Komatsu PC210-10 Crawler Excavator',
    type: 'Heavy machinery',
    model: 'PC210LC-10',
    registrationNo: 'WP-LB-9022',
    capacity: '21.5 Tons / 1.2 m³',
    sourceProject: 'Central Expressway Project (CEP-02)',
    status: 'active',
  },
  {
    code: 'MJCB0034',
    name: 'JCB 3CX Eco Backhoe Loader',
    type: 'Heavy machinery',
    model: '3CX-4T 4WD',
    registrationNo: 'CP-NB-3411',
    capacity: '1.2 m³ Bucket / 4.2m Dig',
    sourceProject: 'Kandy Highway Development',
    status: 'active',
  },
  {
    code: 'MJCB0041',
    name: 'CAT 428F2 Backhoe Loader',
    type: 'Heavy machinery',
    model: '428F2 Sideshift',
    registrationNo: 'WP-NA-7812',
    capacity: '1.03 m³ Bucket / 4.3m Dig',
    sourceProject: 'Central Equipment Yard - Peliyagoda',
    status: 'active',
  },
  {
    code: 'MBLD0012',
    name: 'Komatsu D85ESS-2A Crawler Bulldozer',
    type: 'Earthmoving',
    model: 'D85ESS-2A',
    registrationNo: 'SG-NA-1092',
    capacity: '20.6 Tons / 3.4 m³ Blade',
    sourceProject: 'Southern Expressway Extension',
    status: 'active',
  },
  {
    code: 'MROL0042',
    name: 'Bomag BW211 D-40 Single Drum Roller',
    type: 'Compaction',
    model: 'BW211 D-40',
    registrationNo: 'WP-NC-2940',
    capacity: '11 Tons Static / 24 Tons Dyn',
    sourceProject: 'Central Expressway Project (CEP-02)',
    status: 'active',
  },
  {
    code: 'MROL0055',
    name: 'Hamm 3411 Vibratory Soil Compactor',
    type: 'Compaction',
    model: 'Hamm 3411 V',
    registrationNo: 'WP-ND-8192',
    capacity: '12 Tons / 2.14m Drum',
    sourceProject: 'Colombo Port City Infrastructure',
    status: 'active',
  },
  {
    code: 'MCRN0018',
    name: 'Liebherr 85 EC-B 5 Flat-Top Tower Crane',
    type: 'Crane',
    model: '85 EC-B 5 FR.tronic',
    registrationNo: 'TC-5010-LK',
    capacity: '5.0 Tons Max / 50m Jib',
    sourceProject: 'Colombo Port City Infrastructure',
    status: 'active',
  },
  {
    code: 'MCRN0022',
    name: 'Zoomlion QY50V Mobile Truck Crane 50T',
    type: 'Crane',
    model: 'QY50V532',
    registrationNo: 'WP-DA-3912',
    capacity: '50 Tons / 42m Main Boom',
    sourceProject: 'Central Equipment Yard - Peliyagoda',
    status: 'active',
  },
  {
    code: 'MTRK0056',
    name: 'Isuzu GIGA 10-Wheeler Dump Truck',
    type: 'Transport',
    model: 'FVZ34 6x4',
    registrationNo: 'WP-LJ-6204',
    capacity: '14 m³ / 18 Tons Payload',
    sourceProject: 'Central Expressway Project (CEP-02)',
    status: 'active',
  },
  {
    code: 'MTRK0061',
    name: 'Hino 700 Heavy Tipper Truck 12m³',
    type: 'Transport',
    model: 'FS1E 6x4',
    registrationNo: 'WP-LK-4819',
    capacity: '12 m³ / 16 Tons Payload',
    sourceProject: 'Kandy Highway Development',
    status: 'active',
  },
  {
    code: 'MMIX0025',
    name: 'Schwing Stetter Concrete Batching Plant',
    type: 'Concrete',
    model: 'CP30 Compartment Batcher',
    registrationNo: 'BP-30-PLG',
    capacity: '30 m³/h Output',
    sourceProject: 'Central Equipment Yard - Peliyagoda',
    status: 'active',
  },
  {
    code: 'MPMP0014',
    name: 'Putzmeister BSF 36-4 Truck Boom Pump',
    type: 'Concrete',
    model: 'BSF 36-4.16 H',
    registrationNo: 'WP-QA-8911',
    capacity: '160 m³/h / 36m Reach',
    sourceProject: 'Colombo Port City Infrastructure',
    status: 'active',
  },
  {
    code: 'MACM0075',
    name: 'Ingersoll Rand 750 CFM Air Compressor',
    type: 'Air compressor',
    model: 'XP750WCU-T4F',
    registrationNo: 'CMP-750-01',
    capacity: '750 CFM @ 9 Bar',
    sourceProject: 'Head Office Master Pool',
    status: 'active',
  },
  {
    code: 'MACM0146',
    name: 'Atlas Copco XAS 186 Portable Compressor',
    type: 'Air compressor',
    model: 'XAS 186 Dd',
    registrationNo: 'CMP-400-08',
    capacity: '400 CFM @ 7 Bar',
    sourceProject: 'Kandy Highway Development',
    status: 'active',
  },
  {
    code: 'MACM0163',
    name: 'Sullair 375H Rotary Screw Compressor',
    type: 'Air compressor',
    model: '375H Tier 3',
    registrationNo: 'CMP-375-14',
    capacity: '375 CFM @ 10 Bar',
    sourceProject: 'Southern Expressway Extension',
    status: 'active',
  },
  {
    code: 'MGEN0088',
    name: 'Cummins 150kVA Silent Diesel Generator',
    type: 'Power',
    model: 'C150D5e Enclosed',
    registrationNo: 'GEN-150-03',
    capacity: '150 kVA / 120 kW 3-Phase',
    sourceProject: 'Head Office Master Pool',
    status: 'active',
  },
  {
    code: 'MWEL0091',
    name: 'Lincoln Electric Inverter Welder 400A',
    type: 'Welding',
    model: 'Invertec V400-TP',
    registrationNo: 'WLD-400-22',
    capacity: '400A Multi-Process TIG/MIG',
    sourceProject: 'Central Equipment Yard - Peliyagoda',
    status: 'active',
  },
];

// ── 2. Central Corporate Business Partners Directory ──────────────────────────
export const CORPORATE_PARTNERS_CATALOG: CorporateBusinessPartner[] = [
  {
    code: 'BP-ACC01',
    name: 'Access Engineering PLC',
    type: 'Subcontractor',
    contactPerson: 'Eng. Suneth Wijesinghe',
    phone: '+94 11 2865412',
    email: 'contracts@access.lk',
    address: 'No. 278, Union Place, Colombo 02',
    sourceProject: 'Central Subcontractor Registry',
    rating: 'Tier-1 National',
  },
  {
    code: 'BP-CML02',
    name: 'CML-MTD Construction Ltd',
    type: 'Subcontractor',
    contactPerson: 'Mr. Nimal Dissanayake',
    phone: '+94 11 2589012',
    email: 'tenders@cmlmtd.com',
    address: 'Level 8, World Trade Center, Colombo 01',
    sourceProject: 'Highway Division Pool',
    rating: 'Tier-1 National',
  },
  {
    code: 'BP-NWL03',
    name: 'Nawaloka Construction (Pvt) Ltd',
    type: 'Subcontractor',
    contactPerson: 'Mr. Kamal Perera',
    phone: '+94 11 2698711',
    email: 'procurement@nawaloka.lk',
    address: 'No. 115, Sir James Peiris Mawatha, Colombo 02',
    sourceProject: 'Building Construction Division',
    rating: 'Tier-1 National',
  },
  {
    code: 'BP-SRR04',
    name: 'Sierra Construction (Pvt) Ltd',
    type: 'Subcontractor',
    contactPerson: 'Eng. Pradeep Jayasuriya',
    phone: '+94 11 2789123',
    email: 'info@sierraltd.lk',
    address: 'No. 23, Asoka Gardens, Colombo 04',
    sourceProject: 'Water & Marine Projects',
    rating: 'Tier-1 National',
  },
  {
    code: 'BP-TUD05',
    name: 'Tudawe Brothers (Pvt) Ltd',
    type: 'Subcontractor',
    contactPerson: 'Mr. Jagath Tudawe',
    phone: '+94 11 2871092',
    email: 'contact@tudawe.com',
    address: 'No. 505/2, Elvitigala Mawatha, Colombo 05',
    sourceProject: 'Central Subcontractor Registry',
    rating: 'Tier-1 National',
  },
  {
    code: 'BP-SNK06',
    name: 'Sanken Construction (Pvt) Ltd',
    type: 'Subcontractor',
    contactPerson: 'Eng. Ravi Seneviratne',
    phone: '+94 11 2826733',
    email: 'info@sanken.lk',
    address: 'No. 295, Madampitiya Road, Colombo 14',
    sourceProject: 'Building Construction Division',
    rating: 'Tier-1 National',
  },
  {
    code: 'BP-ICC07',
    name: 'International Construction Consortium (ICC)',
    type: 'Subcontractor',
    contactPerson: 'Mr. Anura Fernando',
    phone: '+94 11 2868112',
    email: 'contracts@icc-construct.com',
    address: 'No. 70, S. De S. Jayasinghe Mawatha, Kohuwala',
    sourceProject: 'Highway Division Pool',
    rating: 'Tier-1 National',
  },
  {
    code: 'BP-VMC11',
    name: 'Venura Metal Crushers (Pvt) Ltd',
    type: 'Supplier',
    contactPerson: 'Mr. Venura Wickramatunga',
    phone: '+94 33 2289100',
    email: 'sales@venuracrushers.lk',
    address: 'Quarry Site, Kotadeniyawa, Mirigama',
    sourceProject: 'Central Expressway Project (CEP-02)',
    rating: 'Certified Quarry Supplier',
  },
  {
    code: 'BP-RBL12',
    name: 'Ranatunga Bar Benders Ltd',
    type: 'Labour Contractor',
    contactPerson: 'Mr. Sarath Ranatunga',
    phone: '+94 77 3489122',
    email: 'ranatunga.steelfix@gmail.com',
    address: 'No. 45, Kandy Road, Kadawatha',
    sourceProject: 'Central Labour Pool - Colombo',
    rating: 'Specialist Rebar Labour',
  },
  {
    code: 'BP-JSE13',
    name: 'Jayasiri Electrical & MEP Services',
    type: 'Specialist MEP',
    contactPerson: 'Eng. Jayasiri Bandara',
    phone: '+94 71 8920199',
    email: 'mep@jayasiri.lk',
    address: 'No. 18, High Level Road, Pannipitiya',
    sourceProject: 'Building Construction Division',
    rating: 'EM-1 Certified',
  },
];

// ── 3. Central Corporate Employee Register ────────────────────────────────────
export const CORPORATE_EMPLOYEES_CATALOG: CorporateEmployee[] = [
  {
    employeeCode: 'EMP-M0101',
    callingName: 'Sunil',
    fullName: 'Sunil Gamage',
    nicNo: '198523401928',
    tradeGroup: 'Carpentry',
    businessPartner: 'Mäga Engineering (Direct)',
    sourceProject: 'Central Labour Pool - Colombo',
    dailyRate: 3500,
    epfNo: 'EPF-89211',
    skillLevel: 'Master Tradesman',
  },
  {
    employeeCode: 'EMP-M0102',
    callingName: 'Bandara',
    fullName: 'K.M. Bandara',
    nicNo: '199014502891',
    tradeGroup: 'Masonry',
    businessPartner: 'Mäga Engineering (Direct)',
    sourceProject: 'Kandy Highway Phase 1',
    dailyRate: 3800,
    epfNo: 'EPF-74102',
    skillLevel: 'Skilled Grade 1',
  },
  {
    employeeCode: 'EMP-M0103',
    callingName: 'Kumara',
    fullName: 'L.A. Kumara',
    nicNo: '198276103429',
    tradeGroup: 'Steel Fixer',
    businessPartner: 'Sierra Construction (Pvt) Ltd',
    sourceProject: 'Central Expressway Project',
    dailyRate: 4200,
    epfNo: 'EPF-90234',
    skillLevel: 'Master Tradesman',
  },
  {
    employeeCode: 'EMP-M0104',
    callingName: 'Pradeep',
    fullName: 'Pradeep Wijeratne',
    nicNo: '199210904512',
    tradeGroup: 'Operator',
    businessPartner: 'Mäga Engineering (Direct)',
    sourceProject: 'Central Equipment Yard - Peliyagoda',
    dailyRate: 4800,
    epfNo: 'EPF-81092',
    skillLevel: 'Certified Heavy Operator',
  },
  {
    employeeCode: 'EMP-M0105',
    callingName: 'Nishantha',
    fullName: 'Nishantha Jayakody',
    nicNo: '198818205634',
    tradeGroup: 'Electrician',
    businessPartner: 'Access Engineering PLC',
    sourceProject: 'Colombo Port City Infrastructure',
    dailyRate: 4500,
    epfNo: 'EPF-65412',
    skillLevel: 'Skilled Grade 1',
  },
  {
    employeeCode: 'EMP-M0106',
    callingName: 'Mahesh',
    fullName: 'Mahesh Senaratne',
    nicNo: '198309104821',
    tradeGroup: 'Welder',
    businessPartner: 'Nawaloka Construction (Pvt) Ltd',
    sourceProject: 'Orugodawatta Flyover Project',
    dailyRate: 4600,
    epfNo: 'EPF-71902',
    skillLevel: '6G Certified Welder',
  },
  {
    employeeCode: 'EMP-M0107',
    callingName: 'Roshan',
    fullName: 'Roshan Wickramasinghe',
    nicNo: '199120409812',
    tradeGroup: 'Bar Bender',
    businessPartner: 'Ranatunga Bar Benders Ltd',
    sourceProject: 'Central Labour Pool - Colombo',
    dailyRate: 3600,
    epfNo: 'EPF-54819',
    skillLevel: 'Skilled Grade 2',
  },
  {
    employeeCode: 'EMP-M0108',
    callingName: 'Chaminda',
    fullName: 'Chaminda Rathnayake',
    nicNo: '198719203841',
    tradeGroup: 'Scaffolder',
    businessPartner: 'Mäga Engineering (Direct)',
    sourceProject: 'Southern Expressway Project',
    dailyRate: 3900,
    epfNo: 'EPF-82914',
    skillLevel: 'Certified Scaffolder',
  },
  {
    employeeCode: 'EMP-M0109',
    callingName: 'Sanjeewa',
    fullName: 'Sanjeewa Alwis',
    nicNo: '198904102941',
    tradeGroup: 'Labour',
    businessPartner: 'Mäga Engineering (Direct)',
    sourceProject: 'Central Labour Pool - Colombo',
    dailyRate: 3000,
    epfNo: 'EPF-91028',
    skillLevel: 'Semi-Skilled Field Labour',
  },
  {
    employeeCode: 'EMP-M0110',
    callingName: 'Dinesh',
    fullName: 'Dinesh Gunawardena',
    nicNo: '199329108421',
    tradeGroup: 'Operator',
    businessPartner: 'Mäga Engineering (Direct)',
    sourceProject: 'Central Equipment Yard - Peliyagoda',
    dailyRate: 5000,
    epfNo: 'EPF-49102',
    skillLevel: 'Tower Crane Certified',
  },
  {
    employeeCode: 'EMP-M0111',
    callingName: 'Ruwan',
    fullName: 'Ruwan Fernando',
    nicNo: '198610204911',
    tradeGroup: 'Carpentry',
    businessPartner: 'Tudawe Brothers (Pvt) Ltd',
    sourceProject: 'Kandy Highway Phase 1',
    dailyRate: 3700,
    epfNo: 'EPF-62910',
    skillLevel: 'Skilled Grade 1',
  },
  {
    employeeCode: 'EMP-M0112',
    callingName: 'Wasantha',
    fullName: 'Wasantha Abeykoon',
    nicNo: '198429103982',
    tradeGroup: 'Masonry',
    businessPartner: 'Sanken Construction (Pvt) Ltd',
    sourceProject: 'Building Construction Division',
    dailyRate: 4000,
    epfNo: 'EPF-78192',
    skillLevel: 'Master Tradesman',
  },
];

// ── 4. Central Corporate Activity Code / BOQ Master ───────────────────────────
export const CORPORATE_ACTIVITY_CATALOG: CorporateActivityCode[] = [
  // ── Screenshot 2: Overheads & Contractor Facilities (00-00-xx-xx) ──
  {
    code: '00-00-00-00',
    description: 'Overheads, Procurement and Contracting Requirements',
    searchKey: 'OVERHEADS, PROCU',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-00-10',
    description: 'Claims',
    searchKey: 'CLAIMS',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-10-00',
    description: 'Site Overheads (SOH)',
    searchKey: 'SITE OVERHEADS (',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-10-10',
    description: 'Overhead cost - Adverse Weather related works',
    searchKey: 'SITE OVERHEADS (',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-10-20',
    description: 'Overhead cost - Consumable',
    searchKey: 'SITE OVERHEADS (',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-11-00',
    description: 'Contractor Facilities and Welfare',
    searchKey: 'CONTRACTOR F',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-11-10',
    description: 'Accommodation & Welfare Facilities - for Contractor',
    searchKey: 'ACCOMMODATIO',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-11-11',
    description: 'Accommodation Facilities - Staff - for Contractor',
    searchKey: 'ACCOMMODATIO',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-11-12',
    description: 'Accommodation Facilities Labour - for Contractor',
    searchKey: 'ACCOMMODATIO',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-11-13',
    description: 'Accommodation & Welfare Facilities - Meals and Tea - for C',
    searchKey: 'ACCOMMODATIO',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-11-14',
    description: 'Accommodation & Welfare Facilities - Mess Expenses',
    searchKey: 'ACCOMMODATIO',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-11-16',
    description: 'Accommodation Facilities - Managers - for Contractor',
    searchKey: 'ACCOMMODATIO',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-11-17',
    description: 'Accommodation Facilities - Operators - for Contractor',
    searchKey: 'ACCOMMODATIO',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-11-19',
    description: 'Welfare Facilities and Entertainment - for Contractor',
    searchKey: 'WELFARE FACI',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-11-20',
    description: 'Establish, Operation, Maintenance & Removing Temporary',
    searchKey: 'ESTABLISH, O',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-11-21',
    description: 'Establish, Operation, Maintenance & Removing - Temporary',
    searchKey: 'ESTABLISH, O',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-11-22',
    description: 'Establish, Operation, Maintenance & Removing Temporary',
    searchKey: 'ESTABLISH, O',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-11-23',
    description: 'Establish, Operation, Maintenance & Removing - Temporary',
    searchKey: 'ESTABLISH, O',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-11-24',
    description: 'Establish, Operation, Maintenance & Removing - Lands and',
    searchKey: 'ESTABLISH, O',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '00-00-11-25',
    description: 'Establish, Operation, Maintenance & Removing Temporary Si',
    searchKey: 'ESTABLISH, O',
    activityType: 'Work Package',
    unit: 'ite',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },

  // ── Screenshot 1: Engineering, Surveying & Construction Works (01-71 / 01-73) ──
  {
    code: '01-71-13-30',
    description: "Mobilization - Sub Contractor's",
    searchKey: 'MOBILIZATION -SU',
    activityType: 'Work Package',
    timeUnit: 's',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-71-13-31',
    description: 'Mobilization & Preliminaries for Pilling',
    searchKey: 'MOBILIZATION -PR',
    activityType: 'Work Package',
    timeUnit: 's',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-71-16-00',
    description: 'Acceptance of Conditions',
    searchKey: 'ACCEPTANCE OF CO',
    activityType: 'Work Package',
    timeUnit: 's',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-71-23-00',
    description: 'Field Engineering',
    searchKey: 'FIELD ENGINEERIN',
    activityType: 'Work Package',
    timeUnit: 's',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-71-23-13',
    description: 'Construction Layout',
    searchKey: 'CONSTRUCTION LAY',
    activityType: 'Work Package',
    timeUnit: 's',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-71-23-16',
    description: 'Construction Surveying',
    searchKey: 'CONSTRUCTION SUR',
    activityType: 'Work Package',
    timeUnit: 's',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-71-23-19',
    description: 'Construction Setting Out Works',
    searchKey: 'CONSTRUCTION SET',
    activityType: 'Work Package',
    unit: 'nos',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-71-33-00',
    description: 'Protection of Adjacent Construction',
    searchKey: 'PROTECTION OF AD',
    activityType: 'Work Package',
    unit: 'nos',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-71-36-00',
    description: 'Non-Destructive Concrete Examination',
    searchKey: 'NON-DESTRUCTIVE',
    activityType: 'Work Package',
    unit: 'nos',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-73-00-00',
    description: 'Execution',
    searchKey: 'EXECUTION',
    activityType: 'Work Package',
    unit: 'nos',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-73-13-00',
    description: 'Application',
    searchKey: 'APPLICATION',
    activityType: 'Work Package',
    unit: 'nos',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-73-16-00',
    description: 'Erection',
    searchKey: 'ERECTION',
    activityType: 'Work Package',
    unit: 'nos',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-73-16-01',
    description: 'Erection of box Girders',
    searchKey: 'ERECTION OF BOX',
    activityType: 'Work Package',
    unit: 'nos',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-73-19-00',
    description: 'Installation',
    searchKey: 'INSTALLATION',
    activityType: 'Work Package',
    unit: 'nos',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-73-23-00',
    description: 'Bracing and Anchoring',
    searchKey: 'BRACING AND ANCH',
    activityType: 'Work Package',
    unit: 'nos',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-73-26-00',
    description: 'Existing Products',
    searchKey: 'EXISTING PRODUCT',
    activityType: 'Work Package',
    unit: 'nos',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-73-29-00',
    description: 'Cutting and Patching',
    searchKey: 'CUTTING AND PATC',
    activityType: 'Work Package',
    unit: 'nos',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-73-31-00',
    description: 'Builders Works',
    searchKey: 'BUILDERS WORKS',
    activityType: 'Work Package',
    unit: 'nos',
    timeUnit: 'hrs',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-73-31-11',
    description: 'Builders Works for Plumbing Facility Construction',
    searchKey: 'BUILDERS WORKS F',
    activityType: 'Work Package',
    unit: 'nos',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
  {
    code: '01-73-31-13',
    description: 'Builders Works for Electrical Facility Construction',
    searchKey: 'BUILDERS WORKS F',
    activityType: 'Work Package',
    unit: 'nos',
    sourceProject: 'Maga - CWS',
    currentWorkingProject: 'Maga - CWS',
  },
];

// ── 5. Central Corporate Projects Master ──────────────────────────────────────
export const CORPORATE_PROJECTS_CATALOG: CorporateProject[] = [
  {
    projectCode: 'M00000427',
    description: '427M -Maga Two',
    searchKey: '427M -MAGA TWO',
    projectManager: 'E0041',
    status: 'Active',
    addressCode: 'MAG000082',
    projectName: '427M - Maga Two',
    enterpriseUnit: 'BDG001',
    divisionType: 'Building Division',
    currency: 'LKR',
  },
  {
    projectCode: 'M00000443',
    description: '443M -ICONIC Galaxy',
    searchKey: '443M -ICONIC GAL',
    projectManager: 'E0072',
    status: 'Active',
    addressCode: 'MAG000108',
    projectName: '443M - ICONIC Residential',
    enterpriseUnit: 'BDG001',
    divisionType: 'Building Division',
    currency: 'LKR',
  },
  {
    projectCode: 'M00000459',
    description: '459M -iRoad -VA1 -Vavuniya',
    searchKey: '459M -IROAD -VA1',
    projectManager: 'E5945',
    status: 'Active',
    addressCode: 'MAG000141',
    projectName: '459M - iRoad -VA1-Vavuniya',
    enterpriseUnit: 'RDS001',
    divisionType: 'Roads Division',
    currency: 'LKR',
  },
  {
    projectCode: 'M00000460',
    description: '460M -iRoad -VA2 -Vavuniya',
    searchKey: '460M -IROAD -VA2',
    projectManager: 'E0035',
    status: 'Active',
    addressCode: 'MAG000142',
    projectName: '460M - iRoad -VA2-Vavuniya',
    enterpriseUnit: 'RDS001',
    divisionType: 'Roads Division',
    currency: 'LKR',
  },
  {
    projectCode: 'M00000461',
    description: '461M -iRoad -VA3 -Vavuniya',
    searchKey: '461M -IROAD -VA3',
    projectManager: 'E0027',
    status: 'Active',
    addressCode: 'MAG000143',
    projectName: '461M - iRoad -VA3-Vavuniya',
    enterpriseUnit: 'RDS001',
    divisionType: 'Roads Division',
    currency: 'LKR',
  },
  {
    projectCode: 'M00000462',
    description: '462M -iRoad -MU1 -Mullaitivu',
    searchKey: '462M -IROAD -MU1',
    projectManager: 'E4523',
    status: 'Active',
    addressCode: 'MAG000144',
    projectName: '462M - iRoad -MU1-Mullaitivu',
    enterpriseUnit: 'RDS001',
    divisionType: 'Roads Division',
    currency: 'LKR',
  },
  {
    projectCode: 'M00000463',
    description: '463M -iRoad -MU2 -Mullaitivu',
    searchKey: '463M -IROAD -MU2',
    projectManager: 'E2392',
    status: 'Active',
    addressCode: 'MAG000145',
    projectName: '463M - iRoad -MU2-Mullaitivu',
    enterpriseUnit: 'RDS001',
    divisionType: 'Roads Division',
    currency: 'LKR',
  },
  {
    projectCode: 'M00000464',
    description: '464M -iRoad -KN3 -Kilinochchi',
    searchKey: '464M -IROAD -KN3',
    projectManager: 'E6335',
    status: 'Active',
    addressCode: 'MAG000146',
    projectName: '464M - iRoad -KN3-Kilinochchi',
    enterpriseUnit: 'RDS001',
    divisionType: 'Roads Division',
    currency: 'LKR',
  },
  {
    projectCode: 'M00000465',
    description: '465M -iRoad -JF1 -Jaffna',
    searchKey: '465M -IROAD -JF1',
    projectManager: 'E2734',
    status: 'Active',
    addressCode: 'MAG000147',
    projectName: '465M - iRoad -JF1-Jaffna',
    enterpriseUnit: 'RDS001',
    divisionType: 'Roads Division',
    currency: 'LKR',
  },
  {
    projectCode: 'M00000466',
    description: '466M -iRoad -JF5 -Jaffna',
    searchKey: '466M -IROAD -JF5',
    projectManager: 'E1030',
    status: 'Active',
    addressCode: 'MAG000148',
    projectName: '466M - iRoad -JF5-Jaffna',
    enterpriseUnit: 'RDS001',
    divisionType: 'Roads Division',
    currency: 'LKR',
  },
  {
    projectCode: 'M00000503',
    description: '503M -Kandy Road 86+100Km',
    searchKey: '503M -KANDY ROAD',
    projectManager: 'E0033',
    status: 'Active',
    addressCode: 'MAG000200',
    projectName: '503M -Kandy Road 86+100Km',
    enterpriseUnit: 'RDS001',
    divisionType: 'Roads Division',
    currency: 'LKR',
  },
  {
    projectCode: 'M00000504',
    description: '504M -Slave Island Flyovers',
    searchKey: '504M -FLYOVERS',
    projectManager: 'E6793',
    status: 'Active',
    addressCode: 'MAG000201',
    projectName: '504M -Slave Island Flyovers',
    enterpriseUnit: 'BRG001',
    divisionType: 'Bridge Division',
    currency: 'LKR',
  },
  {
    projectCode: 'M00000001',
    description: 'Maga - CWS (Central Workshop)',
    searchKey: 'MAGA - CWS',
    projectManager: 'E0001',
    status: 'Active',
    addressCode: 'MAG000001',
    projectName: 'Central Workshop - Walgama, Athurugiriya',
    enterpriseUnit: 'WRK001',
    divisionType: 'Workshop & Plant',
    currency: 'LKR',
  },
];

// Helper to get unique source projects across a list
export function getUniqueSourceProjects(items: { sourceProject?: string; currentWorkingProject?: string }[]): string[] {
  return Array.from(new Set(items.map((i) => i.sourceProject || i.currentWorkingProject || ''))).filter(Boolean).sort();
}

// Helper to get unique categories/trade groups
export function getUniqueCategories(items: { type?: string; tradeGroup?: string; activityType?: string }[]): string[] {
  return Array.from(
    new Set(items.map((i) => i.type || i.tradeGroup || i.activityType || '').filter(Boolean))
  ).sort();
}

